---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by johannes.
--- DateTime: 6/30/18 11:50 AM
---
local string_helper = {}

local function is_empty(s)
    return s == nil or s == ''
end

string_helper.isEmpty = is_empty

return string_helper