---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by johannes.
--- DateTime: 6/19/18 9:12 AM
---
local string_helper = require("helper.string-helper")

function on_item_mined(event)
    local player = game.players[event.player_index]
    local item = event.item_stack
    local name = player.name

    if string_helper.isEmpty(name) then
        name = "<Unnamed Player>"
    end

    player.print(name .. " mined " .. item.count .. " " .. item.name)
end

script.on_event(defines.events.on_player_mined_item, on_item_mined)
